name: "ESLint Annotate"
description: "Lints changed files and annotates pull request diffs with errors and warnings."
inputs:
  repo-token:
    description: "Token used to interact with the Github API."
    required: true
  extensions:
    description: "File extensions to lint. Ex: .js,.jsx,.ts,.tsx"
    default: ".js,.jsx,.ts,.tsx"
    required: false
  files:
    description: "Glob pattern of files to be linted."
    default: "**/*"
    required: false
  ignore:
    description: "Glob pattern to ignore from linting."
    default: "**/node_modules/**"
    required: false
  working-directory:
    description: "Directory where eslint should execute."
    required: false
  quiet:
    description: "Silence annotations for ESLint warnings."
    default: "false"
    required: false
  fail-on-warnings:
    description: "Fail the lint check if warnings are present. Overrides `quiet`."
    default: "false"
    required: false
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: "check-circle"
  color: "yellow"
