name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get pnpm store directory
        id: pnpm-store-path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-store-path.outputs.STORE_PATH }}
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        run: pnpm install
        shell: bash
      - name: Lint
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: "src/**/*"
      - name: Test
        run: npm test -- --coverage
      - name: Build
        run: npm run build
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
